-- Dos Huertos — Datos iniciales
-- Ejecutar en Supabase SQL Editor DESPUÉS de 001_schema.sql y 002_rpc_functions.sql

-- PROVEEDORES
INSERT INTO suppliers (name, phone) VALUES
('Lo Valledor', '+56912345678'),
('Feria Mapocho', '+56912345679'),
('Proveedor Directo', '+56912345680'),
('Distribuidora Central', '+56912345681'),
('Frutícola del Sur', '+56912345682');

-- PRODUCTOS (124 items)
INSERT INTO products (name, category, unit, cost_price, sale_price, min_stock) VALUES

-- FRUTAS (28)
('Arándano','Frutas','kg',0,0,3),
('Cereza','Frutas','kg',0,0,3),
('Chirimoya','Frutas','kg',0,0,3),
('Ciruela','Frutas','kg',0,0,3),
('Damasco','Frutas','kg',0,0,3),
('Durazno','Frutas','kg',0,0,3),
('Frambuesa','Frutas','kg',0,0,3),
('Frutilla','Frutas','kg',0,0,3),
('Higos','Frutas','kg',0,0,3),
('Kiwi','Frutas','kg',0,0,3),
('Mandarina','Frutas','kg',0,0,3),
('Mango','Frutas','kg',0,0,3),
('Manzana Fuji','Frutas','kg',0,0,3),
('Manzana Roja','Frutas','kg',0,0,3),
('Manzana Verde','Frutas','kg',0,0,3),
('Maracuyá','Frutas','kg',0,0,3),
('Melón','Frutas','kg',0,0,3),
('Membrillo','Frutas','kg',0,0,3),
('Mora','Frutas','kg',0,0,3),
('Naranja','Frutas','kg',0,0,3),
('Pepino Dulce','Frutas','kg',0,0,3),
('Pera','Frutas','kg',0,0,3),
('Piña','Frutas','unidad',0,0,3),
('Plátano Ecuador','Frutas','kg',0,0,3),
('Pomelo','Frutas','kg',0,0,3),
('Sandía','Frutas','kg',0,0,3),
('Tuna','Frutas','kg',0,0,3),
('Uva S/P','Frutas','kg',0,0,3),

-- VERDURAS (56)
('Acelga','Verduras','atado',0,0,3),
('Albahaca','Verduras','atado',0,0,3),
('Alcachofa','Verduras','unidad',0,0,3),
('Apio','Verduras','atado',0,0,3),
('Berenjena','Verduras','kg',0,0,3),
('Betarraga','Verduras','kg',0,0,3),
('Brócoli','Verduras','kg',0,0,3),
('Brucelas','Verduras','kg',0,0,3),
('Cebolla Blanca','Verduras','kg',0,0,3),
('Cebolla Morada','Verduras','kg',0,0,3),
('Cebollín','Verduras','atado',0,0,3),
('Champiñón 200gr','Verduras','bandeja',0,0,3),
('Champiñón Granel','Verduras','kg',0,0,3),
('Chapsui','Verduras','atado',0,0,3),
('Choclo Americano','Verduras','unidad',0,0,3),
('Choclo Pastelero','Verduras','unidad',0,0,3),
('Ciboulett','Verduras','atado',0,0,3),
('Cilantro','Verduras','kg',0,0,3),
('Cilantro Atado','Verduras','atado',0,0,3),
('Coliflor','Verduras','kg',0,0,3),
('Espárrago','Verduras','kg',0,0,3),
('Espinaca','Verduras','kg',0,0,3),
('Habas','Verduras','kg',0,0,3),
('Lechuga Bionda','Verduras','unidad',0,0,3),
('Lechuga Bionda Morada','Verduras','unidad',0,0,3),
('Lechuga Costina','Verduras','unidad',0,0,3),
('Lechuga Escarola','Verduras','unidad',0,0,3),
('Lechuga Española','Verduras','unidad',0,0,3),
('Lechuga Lollo Rose','Verduras','unidad',0,0,3),
('Lechuga Marina','Verduras','unidad',0,0,3),
('Lechuga Morada','Verduras','unidad',0,0,3),
('Limón','Verduras','kg',0,0,3),
('Limón Sutil','Verduras','kg',0,0,3),
('Palta Hass Chilena','Verduras','kg',0,0,3),
('Palta Hass Peruana','Verduras','kg',0,0,3),
('Papa Camote','Verduras','kg',0,0,3),
('Papa Limpia','Verduras','kg',0,0,3),
('Pepino','Verduras','kg',0,0,3),
('Perejil','Verduras','atado',0,0,3),
('Pimentón Amarillo','Verduras','kg',0,0,3),
('Pimentón Rojo','Verduras','kg',0,0,3),
('Pimentón Verde','Verduras','kg',0,0,3),
('Plátano Maduro','Verduras','kg',0,0,3),
('Plátano Verde','Verduras','kg',0,0,3),
('Porotos Verdes','Verduras','kg',0,0,3),
('Poroto Granado','Verduras','kg',0,0,3),
('Rabanitos','Verduras','atado',0,0,3),
('Repollo Blanco','Verduras','kg',0,0,3),
('Repollo Morado','Verduras','kg',0,0,3),
('Rúcula','Verduras','atado',0,0,3),
('Tomate Cherry','Verduras','kg',0,0,3),
('Tomate Rojo','Verduras','kg',0,0,3),
('Yuca','Verduras','kg',0,0,3),
('Zanahoria','Verduras','kg',0,0,3),
('Zapallo Camote','Verduras','kg',0,0,3),
('Zapallo Italiano','Verduras','kg',0,0,3),

-- OTROS (31)
('Aceituna Amarga','Otros','kg',0,0,3),
('Aceituna Rellena Pimentón','Otros','kg',0,0,3),
('Aceituna Sevillana','Otros','kg',0,0,3),
('Aceituna Super Extra','Otros','kg',0,0,3),
('Ají en Vinagre','Otros','frasco',0,0,3),
('Ají Verde','Otros','kg',0,0,3),
('Ajo Chino','Otros','kg',0,0,3),
('Almendras','Otros','kg',0,0,3),
('Castañas','Otros','kg',0,0,3),
('Cebolla Escabeche','Otros','kg',0,0,3),
('Cebolla Perla','Otros','kg',0,0,3),
('Charqui','Otros','kg',0,0,3),
('Cochayuyo','Otros','kg',0,0,3),
('Garbanzos','Otros','kg',0,0,3),
('Huevos Bandeja Color Extra','Otros','bandeja',0,0,3),
('Huevos Bandeja Jumbo','Otros','bandeja',0,0,3),
('Huevos Bandeja Super','Otros','bandeja',0,0,3),
('Huesillo','Otros','kg',0,0,3),
('Jengibre','Otros','kg',0,0,3),
('Lentejas','Otros','kg',0,0,3),
('Maní con Sal','Otros','kg',0,0,3),
('Maní sin Sal','Otros','kg',0,0,3),
('Menta Fresca','Otros','atado',0,0,3),
('Mote','Otros','kg',0,0,3),
('Nueces','Otros','kg',0,0,3),
('Pepinillo Dill','Otros','frasco',0,0,3),
('Pepinillo Fino','Otros','frasco',0,0,3),
('Pickle Especial Fino','Otros','frasco',0,0,3),
('Porotos Burros','Otros','kg',0,0,3),
('Porotos Negros','Otros','kg',0,0,3),
('Servilletas','Otros','paquete',0,0,3),

-- INSUMOS (9)
('Acelguera','Insumos','unidad',0,0,3),
('Alusa','Insumos','rollo',0,0,3),
('Arandanera','Insumos','unidad',0,0,3),
('Bolsa Camiseta','Insumos','ciento',0,0,3),
('Bolsa Lechuguera','Insumos','ciento',0,0,3),
('Cilantrera','Insumos','unidad',0,0,3),
('Frutillera','Insumos','unidad',0,0,3),
('Guantes','Insumos','caja',0,0,3),
('Nova','Insumos','caja',0,0,3);
